name: Ping Cloudflare Worker every 2~5 seconds

on:
  schedule:
    - cron: "*/1 * * * *"  # 매분 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  ping_worker:
    runs-on: ubuntu-latest
    steps:
      - name: Send request every 2~5 seconds
        run: |
          end=$((SECONDS+60))  # 1분 동안 실행
          while [ $SECONDS -lt $end ]; do
            curl -s https://green-cake-8f49.mtinet79.workers.dev/
            sleep $((2 + RANDOM % 4))  # 2~5초 랜덤 대기
          done
